import type { SupabaseClient } from '@supabase/supabase-js'
import { Batch } from '@/lib/types/business-types'

// Enhanced types for better type safety and structure
export interface CreateBatchData {
  supplier_id: string
  invoice_number?: string
  invoice_date?: string
  invoice_amount?: number
  device_count: number
  received_date: string
  notes?: string
  created_by: string
}   

export interface BatchWithSupplier extends Batch {
  supplier: {
    name: string
  } | null
  supplier_name?: string
}

export interface BatchFilters {
  supplier_id?: string
  date_from?: string
  date_to?: string
  status?: string
  search?: string
}

/**
 * Batches API with dependency injection pattern
 * Accepts Supabase client as parameter to avoid creating multiple clients
 */
export class BatchesAPI {
  constructor(private supabase: SupabaseClient) {}

  /**
   * Get all batches with supplier information
   */
  async getAll(): Promise<BatchWithSupplier[]> {
    try {
      const { data, error } = await this.supabase
        .from('batches')
        .select(`
          *,
          supplier:suppliers(name)
        `)
        .is('deleted_at', null)
        .order('created_at', { ascending: false })

      if (error) {
        throw new Error(`Failed to fetch batches: ${error.message}`)
      }
      
      // Transform data to include supplier_name
      return data?.map((batch: BatchWithSupplier) => ({
        ...batch,
        supplier_name: batch.supplier?.name
      })) as BatchWithSupplier[]
    } catch (error) {
      console.error('Error in getAll:', error)
      throw error
    }
  }

  /**
   * Get a single batch by ID with supplier information
   */
  async getById(id: string): Promise<BatchWithSupplier> {
    try {
      const { data, error } = await this.supabase
        .from('batches')
        .select(`
          *,
          supplier:suppliers(name)
        `)
        .eq('id', id)
        .is('deleted_at', null)
        .single()

      if (error) {
        throw new Error(`Failed to fetch batch: ${error.message}`)
      }
      
      // Transform data to include supplier_name
      return {
        ...data,
        supplier_name: data.supplier?.name
      } as BatchWithSupplier
    } catch (error) {
      console.error('Error in getById:', error)
      throw error
    }
  }

  /**
   * Create a new batch
   * Batch number is auto-generated by database trigger
   */
  async create(batchData: CreateBatchData): Promise<BatchWithSupplier> {
    try {
      // Note: batch_number is auto-generated by database trigger (format: BATCH-YYYYMMDD-XXX)
      const { data, error } = await this.supabase
        .from('batches')
        .insert({
          ...batchData,
          received_date: batchData.received_date || new Date().toISOString().split('T')[0]
        })
        .select(`
          *,
          supplier:suppliers(name)
        `)
        .single()

      if (error) {
        throw new Error(`Failed to create batch: ${error.message}`)
      }
      
      // Transform data to include supplier_name
      return {
        ...data,
        supplier_name: data.supplier?.name
      } as BatchWithSupplier
    } catch (error) {
      console.error('Error in create:', error)
      throw error
    }
  }

  /**
   * Update an existing batch
   */
  async update(id: string, batchData: Partial<{
    supplier_id: string
    invoice_number: string
    invoice_date: string
    invoice_amount: number
    device_count: number
    received_date: string
    notes: string
  }>) {
    const { data, error } = await this.supabase
      .from('batches')
      .update({
        ...batchData,
        updated_at: new Date().toISOString()
      })
      .eq('id', id)
      .select(`
        *,
        supplier:suppliers(name)
      `)
      .single()

    if (error) throw error
    
    // Transform data to include supplier_name
    return {
      ...data,
      supplier_name: data.supplier?.name
    } as Batch
  }

  /**
   * Delete a batch (soft delete)
   */
  async delete(id: string) {
    const { error } = await this.supabase
      .from('batches')
      .update({ deleted_at: new Date().toISOString() })
      .eq('id', id)

    if (error) throw error
    return true
  }

  /**
   * Get batch with all its devices
   */
  async getBatchWithDevices(id: string) {
    const { data, error } = await this.supabase
      .from('batches')
      .select(`
        *,
        supplier:suppliers(name),
        devices(*)
      `)
      .eq('id', id)
      .is('deleted_at', null)
      .single()

    if (error) throw error
    
    // Transform data to include supplier_name
    return {
      ...data,
      supplier_name: data.supplier?.name
    }
  }

  /**
   * Get batches with device counts and completed QC counts
   */
  async getAllWithDeviceCounts() {
    // Get all batches with supplier info
    const { data: batches, error: batchesError } = await this.supabase
      .from('batches')
      .select(`
        *,
        supplier:suppliers(name)
      `)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })

    if (batchesError) throw batchesError

    // Get device counts for all batches in one query
    const { data: deviceCounts, error: deviceCountsError } = await this.supabase
      .from('devices')
      .select('batch_id')
      .is('deleted_at', null)

    if (deviceCountsError) throw deviceCountsError

    // Count devices per batch manually
    const deviceCountMap = new Map<string, number>()
    deviceCounts?.forEach((device: { batch_id: string }) => {
      const currentCount = deviceCountMap.get(device.batch_id) || 0
      deviceCountMap.set(device.batch_id, currentCount + 1)
    })
    
    // Count all devices per batch (this will be the "Completed QC" count)
    // We already have the device counts from the previous query, so we can use that
    const qcCountMap = deviceCountMap

    // Combine the data
    const result = batches?.map((batch: Batch & { supplier: { name: string } }) => ({
      ...batch,
      supplier_name: batch.supplier?.name,
      completed_qc_count: qcCountMap.get(batch.id) || 0
    })) as (Batch & { 
      completed_qc_count: number 
    })[]

    return result
  }
}

/**
 * Factory function to create BatchesAPI instance with client
 * This maintains backward compatibility while implementing dependency injection
 */
export function createBatchesAPI(supabase: SupabaseClient): BatchesAPI {
  return new BatchesAPI(supabase)
}

/**
 * Legacy singleton instance for backward compatibility
 * @deprecated Use createBatchesAPI() with dependency injection instead
 */
import { createSupabaseClient } from '@/lib/supabase/client'
export const batchesApi = new BatchesAPI(createSupabaseClient()! as unknown as SupabaseClient)