import { createClient } from '@/lib/supabase/client'
import { Batch } from '@/lib/types/business-types'

export const batchesApi = {
  /**
   * Get all batches with supplier information
   */
  async getAll() {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('batches')
      .select(`
        *,
        supplier:suppliers(name)
      `)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })

    if (error) throw error
    
    // Transform data to include supplier_name
    return data?.map((batch: Batch & { supplier: { name: string } }) => ({
      ...batch,
      supplier_name: batch.supplier?.name
    })) as Batch[]
  },

  /**
   * Get a single batch by ID with supplier information
   */
  async getById(id: string) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('batches')
      .select(`
        *,
        supplier:suppliers(name)
      `)
      .eq('id', id)
      .is('deleted_at', null)
      .single()

    if (error) throw error
    
    // Transform data to include supplier_name
    return {
      ...data,
      supplier_name: data.supplier?.name
    } as Batch
  },

  /**
   * Create a new batch
   * Batch number is auto-generated by database trigger
   */
  async create(batchData: {
    supplier_id: string
    invoice_number?: string
    invoice_date?: string
    invoice_amount?: number
    device_count: number
    received_date: string
    notes?: string
    created_by: string
  }) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    // Note: batch_number is auto-generated by database trigger (format: BATCH-YYYYMMDD-XXX)
    const { data, error } = await supabase
      .from('batches')
      .insert({
        ...batchData,
        received_date: batchData.received_date || new Date().toISOString().split('T')[0]
      })
      .select(`
        *,
        supplier:suppliers(name)
      `)
      .single()

    if (error) throw error
    
    // Transform data to include supplier_name
    return {
      ...data,
      supplier_name: data.supplier?.name
    } as Batch
  },

  /**
   * Update an existing batch
   */
  async update(id: string, batchData: Partial<{
    supplier_id: string
    invoice_number: string
    invoice_date: string
    invoice_amount: number
    device_count: number
    received_date: string
    notes: string
  }>) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('batches')
      .update({
        ...batchData,
        updated_at: new Date().toISOString()
      })
      .eq('id', id)
      .select(`
        *,
        supplier:suppliers(name)
      `)
      .single()

    if (error) throw error
    
    // Transform data to include supplier_name
    return {
      ...data,
      supplier_name: data.supplier?.name
    } as Batch
  },

  /**
   * Delete a batch (soft delete)
   */
  async delete(id: string) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { error } = await supabase
      .from('batches')
      .update({ deleted_at: new Date().toISOString() })
      .eq('id', id)

    if (error) throw error
    return true
  },

  /**
   * Get batch with all its devices
   */
  async getBatchWithDevices(id: string) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('batches')
      .select(`
        *,
        supplier:suppliers(name),
        devices(*)
      `)
      .eq('id', id)
      .is('deleted_at', null)
      .single()

    if (error) throw error
    
    // Transform data to include supplier_name
    return {
      ...data,
      supplier_name: data.supplier?.name
    }
  },

  /**
   * Get batches with device counts and completed QC counts
   */
  async getAllWithDeviceCounts() {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    // Get all batches with supplier info
    const { data: batches, error: batchesError } = await supabase
      .from('batches')
      .select(`
        *,
        supplier:suppliers(name)
      `)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })

    if (batchesError) throw batchesError

    // Get device counts for all batches in one query
    const { data: deviceCounts, error: deviceCountsError } = await supabase
      .from('devices')
      .select('batch_id')
      .is('deleted_at', null)

    if (deviceCountsError) throw deviceCountsError

    // Count devices per batch manually
    const deviceCountMap = new Map<string, number>()
    deviceCounts?.forEach((device: { batch_id: string }) => {
      const currentCount = deviceCountMap.get(device.batch_id) || 0
      deviceCountMap.set(device.batch_id, currentCount + 1)
    })
    
    // Count all devices per batch (this will be the "Completed QC" count)
    // We already have the device counts from the previous query, so we can use that
    const qcCountMap = deviceCountMap

    // Combine the data
    const result = batches?.map((batch: Batch & { supplier: { name: string } }) => ({
      ...batch,
      supplier_name: batch.supplier?.name,
      completed_qc_count: qcCountMap.get(batch.id) || 0
    })) as (Batch & { 
      completed_qc_count: number 
    })[]

    return result
  }
}