import { createSupabaseClient } from '@/lib/supabase/client'
import { Device, DeviceStatus, DeviceGrade, DrPhoneData } from '@/lib/types/business-types'
import { DEVICE_STATUS } from '@/lib/constants'
import type { SupabaseClient } from '@supabase/supabase-js'

export interface CreateDeviceData {
  batch_id: string
  imei: string
  serial_number?: string
  brand?: string
  model?: string
  color?: string
  storage_capacity?: string
  dr_phone_data?: DrPhoneData
  notes?: string
}

/**
 * Optimized Devices API with singleton Supabase client
 */
class DevicesAPI {
  private client: SupabaseClient | null = null

  /**
   * Get or create the singleton Supabase client
   */
  private getClient(): SupabaseClient {
    if (!this.client) {
      this.client = createSupabaseClient()
    }
    
    if (!this.client) {
      throw new Error('Supabase client not initialized')
    }
    
    return this.client
  }
  /**
   * Get all devices
   */
  async getAll() {
    const supabase = this.getClient()

    const { data, error } = await supabase
      .from('devices')
      .select('*')
      .is('deleted_at', null)
      .order('created_at', { ascending: false })

    if (error) throw error
    return data as Device[]
  }

  /**
   * Get devices by batch ID
   */
  async getByBatchId(batchId: string) {
    const supabase = this.getClient()

    const { data, error } = await supabase
      .from('devices')
      .select('*')
      .eq('batch_id', batchId)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })

    if (error) throw error
    return data as Device[]
  }

  /**
   * Get a single device by ID
   */
  async getById(id: string) {
    const supabase = this.getClient()

    const { data, error } = await supabase
      .from('devices')
      .select('*')
      .eq('id', id)
      .is('deleted_at', null)
      .single()

    if (error) throw error
    return data as Device
  }

  /**
   * Get a single device by internal ID
   */
  async getByInternalId(internalId: string) {
    const supabase = this.getClient()

    const { data, error } = await supabase
      .from('devices')
      .select(`
        *,
        batch:batches(
          id,
          batch_number,
          supplier:suppliers(name),
          received_date,
          notes
        )
      `)
      .eq('internal_id', internalId)
      .is('deleted_at', null)
      .single()

    if (error) throw error
    return data as Device & {
      batch: {
        id: string
        batch_number: string
        supplier: { name: string }
        received_date: string
        notes?: string
      }
    }
  }

  /**
   * Create a new device
   */
  async create(deviceData: CreateDeviceData) {
    const supabase = this.getClient()

    // Get current user for created_by field
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) throw new Error('User not authenticated')

    // Note: internal_id is auto-generated by database trigger
    const { data, error } = await supabase
      .from('devices')
      .insert({
        ...deviceData,
        status: DEVICE_STATUS.awaiting_repair as DeviceStatus, // Changed from 'received' to 'awaiting_repair'
        grade: 'ungraded' as DeviceGrade,
        created_by: user.id,
        dr_phone_imported_at: deviceData.dr_phone_data ? new Date().toISOString() : undefined
      })
      .select()
      .single()

    if (error) throw error
    return data as Device
  }

  /**
   * Create multiple devices from imported data
   */
  async createFromImport(batchId: string, devices: Array<{
    imei: string
    brand?: string
    model?: string
    serial_number?: string
    dr_phone_data?: DrPhoneData
    grade?: string
    notes?: string
  }>) {
    const supabase = this.getClient()

    // Get current user for created_by field
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) throw new Error('User not authenticated')

    const devicesToCreate = devices.map(device => ({
      batch_id: batchId,
      imei: device.imei,
      brand: device.brand,
      model: device.model,
      serial_number: device.serial_number,
      dr_phone_data: device.dr_phone_data,
      grade: device.grade || 'ungraded', // Use provided grade or default to 'ungraded'
      notes: device.notes,
      status: device.grade !== 'ungraded' ? 'final_qc' as DeviceStatus : 'awaiting_repair' as DeviceStatus, // Changed from 'received' to 'awaiting_repair' if picked repairs, else 'graded'
      created_by: user.id,
      dr_phone_imported_at: new Date().toISOString()
    }))

    const { data, error } = await supabase
      .from('devices')
      .insert(devicesToCreate)
      .select()

    if (error) throw error
    if(data[0].status === DEVICE_STATUS.final_qc) {
      //add device to final qc_check table
       const { error: qcCheckError } = await supabase
      .from('qc_checks')
      .insert({
        device_id: data[0].id,
        check_type: 'final',
        overall_result: 'not_tested',
        performed_by: user.id,
        notes: `Device sent to final QC after completing grading`
      })

      if (qcCheckError) throw qcCheckError
    }
    return data as Device[]
  }

  /**
   * Update a device
   */
  async update(id: string, deviceData: Partial<CreateDeviceData>) {
    const supabase = this.getClient()

    const { data, error } = await supabase
      .from('devices')
      .update({
        ...deviceData,
        updated_at: new Date().toISOString()
      })
      .eq('id', id)
      .select()
      .single()

    if (error) throw error
    return data as Device
  }

  /**
   * Update device status
   */
  async updateStatus(id: string, status: DeviceStatus, _notes?: string) {
    const supabase = this.getClient()

    const { data, error } = await supabase
      .from('devices')
      .update({ 
        status,
        updated_at: new Date().toISOString()
      })
      .eq('id', id)
      .select()
      .single()

    if (error) throw error
    return data as Device
  }

  /**
   * Update device grade
   */
  async updateGrade(id: string, grade: DeviceGrade) {
    const supabase = this.getClient()

    const { data, error } = await supabase
      .from('devices')
      .update({ 
        grade,
        updated_at: new Date().toISOString()
      })
      .eq('id', id)
      .select()
      .single()

    if (error) throw error
    return data as Device
  }

  /**
   * Delete a device (soft delete)
   */
  async delete(id: string) {
    const supabase = this.getClient()

    const { error } = await supabase
      .from('devices')
      .update({ deleted_at: new Date().toISOString() })
      .eq('id', id)

    if (error) throw error
    return true
  }

  /**
   * Get devices that need final QC
   */
  async getDevicesForFinalQC() {
    const supabase = this.getClient()

    // Get devices that are in 'final_qc' status
    const { data, error } = await supabase
      .from('devices')
      .select('*')
      .eq('status', 'final_qc')
      .is('deleted_at', null)
      .order('created_at', { ascending: false })

    if (error) throw error
    return data as Device[]
  }

  /**
   * Get QC checks for devices
   */
  async getQCChecks(deviceIds?: string[]) {
    const supabase = this.getClient()

    // If no device IDs provided or empty array, return empty array instead of all QC checks
    if (!deviceIds || deviceIds.length === 0) {
      return []
    }

    const { data, error } = await supabase
      .from('qc_checks')
      .select('*')
      .in('device_id', deviceIds)
      .order('created_at', { ascending: false })

    if (error) {
      console.error('Supabase query error:', error)
      throw error
    }
    
    return data
  }

  /**
   * Get device status history
   */
  async getDeviceStatusHistory(deviceId: string) {
    const supabase = this.getClient()

    // First get the status history
    const { data: statusHistory, error: historyError } = await supabase
      .from('device_status_history')
      .select('*')
      .eq('device_id', deviceId)
      .order('created_at', { ascending: false })

    if (historyError) throw historyError

    // If no history, return empty array
    if (!statusHistory || statusHistory.length === 0) {
      return []
    }

    // Get unique user IDs from the history
    const userIds = [...new Set(statusHistory
      .map((history: { changed_by: string }) => history.changed_by)
      .filter(Boolean)
    )]

    // If no user IDs, return history without user data
    if (userIds.length === 0) {
      return statusHistory
    }

    // Get user profiles for the found user IDs
    const { data: userProfiles, error: userError } = await supabase
      .from('user_profiles')
      .select('id, full_name, role, technician_level')
      .in('id', userIds)

    if (userError) {
      console.error('Error fetching user profiles:', userError)
      // Return history without user data if user fetch fails
      return statusHistory
    }

    // Create a map of user ID to user profile
    const userMap = new Map(userProfiles.map((user: { id: string }) => [user.id, user]))

    // Combine history with user data
    const enrichedHistory = statusHistory.map((history: { changed_by: string }) => ({
      ...history,
      changed_by_user: history.changed_by ? userMap.get(history.changed_by) : null
    }))

    return enrichedHistory
  }
}

// Export singleton instance
export const devicesApi = new DevicesAPI()
