import { createClient } from '@/lib/supabase/client'
import { Device, DeviceStatus, DeviceGrade, DrPhoneData } from '@/lib/types/business-types'

export interface CreateDeviceData {
  batch_id: string
  imei: string
  serial_number?: string
  brand?: string
  model?: string
  color?: string
  storage_capacity?: string
  dr_phone_data?: DrPhoneData
  notes?: string
}

export const devicesApi = {
  /**
   * Get all devices
   */
  async getAll() {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('devices')
      .select('*')
      .is('deleted_at', null)
      .order('created_at', { ascending: false })

    if (error) throw error
    return data as Device[]
  },

  /**
   * Get devices by batch ID
   */
  async getByBatchId(batchId: string) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('devices')
      .select('*')
      .eq('batch_id', batchId)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })

    if (error) throw error
    return data as Device[]
  },

  /**
   * Get a single device by ID
   */
  async getById(id: string) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('devices')
      .select('*')
      .eq('id', id)
      .is('deleted_at', null)
      .single()

    if (error) throw error
    return data as Device
  },

  /**
   * Get a single device by internal ID
   */
  async getByInternalId(internalId: string) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('devices')
      .select(`
        *,
        batch:batches(
          id,
          batch_number,
          supplier:suppliers(name),
          received_date,
          notes
        )
      `)
      .eq('internal_id', internalId)
      .is('deleted_at', null)
      .single()

    if (error) throw error
    return data as Device & {
      batch: {
        id: string
        batch_number: string
        supplier: { name: string }
        received_date: string
        notes?: string
      }
    }
  },

  /**
   * Create a new device
   */
  async create(deviceData: CreateDeviceData) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    // Get current user for created_by field
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) throw new Error('User not authenticated')

    // Note: internal_id is auto-generated by database trigger
    const { data, error } = await supabase
      .from('devices')
      .insert({
        ...deviceData,
        status: 'received' as DeviceStatus,
        grade: 'ungraded' as DeviceGrade,
        created_by: user.id,
        dr_phone_imported_at: deviceData.dr_phone_data ? new Date().toISOString() : undefined
      })
      .select()
      .single()

    if (error) throw error
    return data as Device
  },

  /**
   * Create multiple devices from imported data
   */
  async createFromImport(batchId: string, devices: Array<{
    imei: string
    brand?: string
    model?: string
    serial_number?: string
    dr_phone_data?: DrPhoneData
    grade?: string
    notes?: string
  }>) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    // Get current user for created_by field
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) throw new Error('User not authenticated')

    const devicesToCreate = devices.map(device => ({
      batch_id: batchId,
      imei: device.imei,
      brand: device.brand,
      model: device.model,
      serial_number: device.serial_number,
      dr_phone_data: device.dr_phone_data,
      grade: device.grade || 'ungraded', // Use provided grade or default to 'ungraded'
      notes: device.notes,
      status: 'received' as DeviceStatus,
      created_by: user.id,
      dr_phone_imported_at: new Date().toISOString()
    }))

    const { data, error } = await supabase
      .from('devices')
      .insert(devicesToCreate)
      .select()

    if (error) throw error
    return data as Device[]
  },

  /**
   * Update a device
   */
  async update(id: string, deviceData: Partial<CreateDeviceData>) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('devices')
      .update({
        ...deviceData,
        updated_at: new Date().toISOString()
      })
      .eq('id', id)
      .select()
      .single()

    if (error) throw error
    return data as Device
  },

  /**
   * Update device status
   */
  async updateStatus(id: string, status: DeviceStatus, _notes?: string) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('devices')
      .update({ 
        status,
        updated_at: new Date().toISOString()
      })
      .eq('id', id)
      .select()
      .single()

    if (error) throw error
    return data as Device
  },

  /**
   * Update device grade
   */
  async updateGrade(id: string, grade: DeviceGrade) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { data, error } = await supabase
      .from('devices')
      .update({ 
        grade,
        updated_at: new Date().toISOString()
      })
      .eq('id', id)
      .select()
      .single()

    if (error) throw error
    return data as Device
  },

  /**
   * Delete a device (soft delete)
   */
  async delete(id: string) {
    const supabase = createClient()
    if (!supabase) throw new Error('Supabase client not initialized')

    const { error } = await supabase
      .from('devices')
      .update({ deleted_at: new Date().toISOString() })
      .eq('id', id)

    if (error) throw error
    return true
  }
}


