version: "3.8"

##############################################################################
#                           SERVICES                                         #
##############################################################################

services:
######################################### Required Services
  supabase-proxy:
    build:
      context: ../../..
      dockerfile: ./docker/${DOCKER_ENV_TYPE}/proxy/Dockerfile
    image: ${HUB_REPOSITORY_DOMAIN}${COMPOSE_PROJECT_NAME}-proxy:${BUILD_NUMBER:-latest}