events {}

http {
    map $http_origin $cors_origin {
        default '';
        "http://localhost:3000"        "http://localhost:3000";
        "https://workflow.remobile.eu" "https://workflow.remobile.eu";
    }
    server {
        listen 80;
        server_name _; 
        
        location / {
            proxy_pass https://xlbmlntytzxrsrvctzxj.supabase.co;
            proxy_set_header Host xlbmlntytzxrsrvctzxj.supabase.co;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_name xlbmlntytzxrsrvctzxj.supabase.co;
            proxy_ssl_server_name on;

            proxy_pass_request_headers on;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header apikey $http_apikey;
            proxy_set_header Content-Type $http_content_type;

            proxy_hide_header Access-Control-Allow-Origin;
            proxy_hide_header Access-Control-Allow-Methods;
            proxy_hide_header Access-Control-Allow-Headers;
            proxy_hide_header Access-Control-Allow-Credentials;
            proxy_hide_header Access-Control-Expose-Headers;
            proxy_hide_header Access-Control-Max-Age;

            add_header 'Access-Control-Allow-Origin' $cors_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
            add_header 'Access-Control-Allow-Headers' "$http_access_control_request_headers" always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;

            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' $cors_origin always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
                add_header 'Access-Control-Allow-Headers' "$http_access_control_request_headers" always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                add_header 'Access-Control-Max-Age' 1728000 always;
                add_header 'Content-Length' 0 always;
                add_header 'Content-Type' 'text/plain charset=UTF-8' always;
                return 204;
            }
        }
    }
}