import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // MVP Documentation sidebar - now autogenerated with _category_.json
  mvpSidebar: [{type: 'autogenerated', dirName: 'tech-docs-mvp'}],
  
  // Future Scopes sidebar - now autogenerated with _category_.json
  futureSidebar: [{type: 'autogenerated', dirName: 'tech-docs-future'}],
  
  // Development sidebar - now autogenerated with _category_.json
  devSidebar: [{type: 'autogenerated', dirName: 'for-developers'}],
  
  // User Manual sidebar - now autogenerated with _category_.json
  userManualSidebar: [{type: 'autogenerated', dirName: 'user-manual'}],
};

export default sidebars;
